language: generic
sudo: required
services: 
  - docker

before_install:
  - docker build -t dsknudsen/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true dsknudsen/docker-react npm run test